language : cpp
dist: trusty
os: 
  - linux
  - osx
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
  - export GOPATH=`pwd`/gosrc
  - export PATH=`pwd`/gosrc/bin:$PATH
  - go get qpm.io/qpm
  - find $GOPATH
script:
  - echo $TRAVIS_OS_NAME
  - git clone https://github.com/benlau/qtci.git
  - source qtci/path.env
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-osx.sh; fi

