language : cpp
sudo: true
dist: trusty
sudo: required
os:
  - linux
#  - osx
addons:
  - apt:
    packages:
    - patchelf
    - libgstreamer-plugins-base0.10-0
  - artifacts: true
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
  - export GOPATH=`pwd`/gosrc
  - export PATH=`pwd`/gosrc/bin:$PATH
  - go get qpm.io/qpm
script:
  - echo $TRAVIS_OS_NAME
  - export ROOTDIR=`pwd`
  - export SRCDIR=`pwd`/sparkqml/app/sparkqml
  - export BUILDDIR=`pwd`/build/sparkqml
  - export INSTALLDIR=`pwd`/build/sparkqml-install
  - export BINDIR=`pwd`/bin
  - mkdir -p $BINDIR
  - git clone https://github.com/benlau/qtci.git
  - source qtci/path.env
  - export PATH=$BINDIR:$PATH
  - export ARTIFACTS_PATHS=$ROOTDIR/artifacts
  - mkdir -p $ROOTDIR/artifacts
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-linux.sh; fi
  - ls $ARTIFACTS_PATHS
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - export ARTIFACTS_TARGET_PATHS="artifacts"
  - artifacts upload

