language : cpp
sudo: true
dist: trusty
sudo: required
os:
  - linux
  - osx
addons:
  - apt:
    packages:
    - patchelf
    - libgstreamer-plugins-base0.10-0
  - artifacts:
    - debug: true
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
  - export GOPATH=`pwd`/gosrc
  - export PATH=`pwd`/gosrc/bin:$PATH
  - go get qpm.io/qpm
  - find $GOPATH
script:
  - echo $TRAVIS_OS_NAME
  - git clone https://github.com/benlau/qtci.git
  - source qtci/path.env
  - export ROOTDIR=`pwd`
  - export SRCDIR=`pwd`/sparkqml/app/sparkqml
  - export BUILDDIR=`pwd`/build/sparkqml
  - export BINDIR=`pwd`/bin
  - mkdir -p $BINDIR
  - export PATH=$BINDIR:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-linux.sh; fi

