language : cpp
dist: trusty
os: 
  - linux
  - osx
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
  - export GOPATH=`pwd`/gosrc
  - export PATH=`pwd`/gosrc/bin:$PATH
  - go get qpm.io/qpm
  - find $GOPATH
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; ./build-osx.sh; fi

